packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': set this to true or false
  '@swc/core': true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
